### ISSUE TITLE
Fully port elasticlunr to rust as a wasm module?

### ISSUE THREAD

**Issue by Jieiku** [mattico/elasticlunr-rs#43]
My understanding is that elasticlunr-rs provides a way to use rust to build the search index (which is what zola uses this for)

Then zola uses the regular elasticlunr.js for web search, search box here: https://www.getzola.org/themes/

There are two rust(WASM) based searches [stork](https://github.com/jameslittle230/stork) and [tinysearch](https://github.com/mre/tinysearch), but it seems elasticlunr is more complete in terms of CJK/stemmers/stopwords.

My experience with WASM is very minimal, but I would think this may reduce the size of the index/search module and because its in WebAssembly I would think it would be more performant than the javascript based elasticlunr, currently my search has zero performance issues, but I am wondering how it would do on a very large site, you can see my current implementation here: https://jieiku.github.io/abridge-demo/ (search for zola and press enter or the search icon)

I could be wrong about some of this as my experience with WASM is minimal, so any information is appreciated.

**Comment by mattico** [comment]
Adding better language support to either of those searchers should be easier than adding a search implementation to this and porting it to WASM.

I also have minimal experience with WASM, but I would expect that elasticlunr's index design is not good for being sped up by WASM. The index is a series of nested maps. I'd expect map lookup to be highly optimized in JavaScript since it's so fundamental to the language. You could try to create an alternate index format but that's outside the scope of this crate.

I'm not particularly interested in implementing this, nor in supporting someone else's implementation. No harm in asking though!

**Comment by Jieiku** [comment]
Thank you for taking the time to write a detailed explanation, I now have a much better understanding of the situation.
